spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: journaldb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${JAVA_EMAIL}
    password: ${JAVA_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com



server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /journal

weather:
  api:
     Key: ${WEATHER_API_KEY}


Spring:
  redis:
    host: ${REDIS_HOST}
    port: 12026
    password: ${REDIS_PASSWORD}
    timeout: 60000